### ISSUE TITLE
能否有更详细的参数说明？

### ISSUE THREAD

**Issue by YonkaFang** [zhranklin/ydiff#1]
以 `--k8s` 为例，这个能关掉吗？怎么关？

```yaml
a: 1
```

```yaml
a: 2
```

我理解，关掉`as k8s resource`后能比较“plain yaml”吧

**Comment by zhranklin** [comment]
1. 所有选项不指定的情况下就是默认不启用的, 不过`--k8s`比较特殊, 当source指定为k8s集群的时候会自动启用。
2. `--k8s`选项的实际作用是: 决定source和target中yaml doc的对应关系, 启用`--k8s`表示会获取kind、name、namespace字段, 将这些字段相同的资源进行对比, 而不启用`--k8s`就比较适合k8s场景外的纯yaml对比, 它是按照顺序的, source中的第一个doc与target的第一个doc对比, 以此类推...
3. 如果要得到更"plain"的对比, 可以启用`--no-rule --no-expand-text`两个选项

以上内容后续考虑加入到`-h`的内容中
